version: '3.7'

services:
  smartbin-backend:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 443:8000
    environment:
      - DATABASE_URL=postgresql://smartbin:smartbinadmin@db/smartbindb
      - MONGODB_URI=mongodb://dragonhack:e0h2fgq3LumCYSrUwiq0J5T5o7QhKZAn7uGQgmq7qNqwsGM14znkiPXwpZf5jXQBC7NW6lLVQHEIAdIk6Tl4dQ==@dragonhack.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@dragonhack@
      - MSV_SUBSCRIPTION_KEY=cf9a3942000344e9ac4f1a54771f6314
      - MSV_ENDPOINT=https://dragonhack-img.cognitiveservices.azure.com/
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=smartbin
      - POSTGRES_PASSWORD=smartbinadmin
      - POSTGRES_DB=smartbindb

volumes:
  postgres_data: