version: '3.7'

services:
  smartbin-backend:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://smartbin:smartbinadmin@db/smartbindb
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=smartbin
      - POSTGRES_PASSWORD=smartbinadmin
      - POSTGRES_DB=smartbindb

volumes:
  postgres_data: